// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPwzXFQL5st4cwdyxYME-N6CU4zykFo4c',
    appId: '1:752671683210:web:2f3e31c413b5fb351d7373',
    messagingSenderId: '752671683210',
    projectId: 'firebase-facilitor-example',
    authDomain: 'fir-facilitor-example.firebaseapp.com',
    storageBucket: 'firebase-facilitor-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfUEooCOtK_euMIZf4pnC1Va33jZeBWqI',
    appId: '1:752671683210:android:8c22d13dc74403d71d7373',
    messagingSenderId: '752671683210',
    projectId: 'firebase-facilitor-example',
    storageBucket: 'firebase-facilitor-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjZtdRPACehgMw2QwRVakPb6moiXqT930',
    appId: '1:752671683210:ios:362e938c01c54ada1d7373',
    messagingSenderId: '752671683210',
    projectId: 'firebase-facilitor-example',
    storageBucket: 'firebase-facilitor-example.appspot.com',
    iosBundleId: 'com.example.firebaseFacilitatorExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjZtdRPACehgMw2QwRVakPb6moiXqT930',
    appId: '1:752671683210:ios:362e938c01c54ada1d7373',
    messagingSenderId: '752671683210',
    projectId: 'firebase-facilitor-example',
    storageBucket: 'firebase-facilitor-example.appspot.com',
    iosBundleId: 'com.example.firebaseFacilitatorExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPwzXFQL5st4cwdyxYME-N6CU4zykFo4c',
    appId: '1:752671683210:web:f102cbd340997cf31d7373',
    messagingSenderId: '752671683210',
    projectId: 'firebase-facilitor-example',
    authDomain: 'fir-facilitor-example.firebaseapp.com',
    storageBucket: 'firebase-facilitor-example.appspot.com',
  );
}
